### ISSUE TITLE
mix format fails with 0.6.1

### ISSUE THREAD

**Issue by Kitton** [hrzndhrn/recode#71]
Hello after updating to version `0.6.1` (from `0.5.1`) the command `mix format` started to fail with this error 
```elixir
** (UndefinedFunctionError) function Recode.Task.Format.config/1 is undefined or private
    (recode 0.6.1) Recode.Task.Format.config(:check)
    (recode 0.6.1) lib/recode/runner/impl.ex:174: anonymous fn/1 in Recode.Runner.Impl.tasks/3
    (elixir 1.15.5) lib/enum.ex:4393: Enum.reject_list/2
    (recode 0.6.1) lib/recode/runner/impl.ex:22: Recode.Runner.Impl.run/3
    (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.15.5) lib/mix/tasks/format.ex:619: Mix.Tasks.Format.format_file/2
    (elixir 1.15.5) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.5) lib/task/supervised.ex:36: Task.Supervised.reply/4
```

Recode config was updated with `mix recode.gen.config` and command `mix recode` keeps working fine

**Comment by NickNeck** [comment]
Thanks for reporting. I will take a look.
