### ISSUE TITLE
mix format failed for file: .iex.exs

### ISSUE THREAD

**Issue by ndan** [hrzndhrn/recode#94]
mix format is broken when the `.iex.exs` file is present in the project.

```
❯ mix format
mix format failed for file: .iex.exs
** (MatchError) no match of right hand side value: {#Sourceror.Zipper<
   #root
   {:alias, [trailing_comments: [], leading_comments: [], end_of_expression: [newlines: 1, line: 1, column: 20], line: 1, column: 1], [{:__aliases__, [trailing_comments: [], leading_comments: [], last: [line: 1, column: 11], line: 1, column: 7], [:App, :PullStats]}]}
 >, [{:alias, [trailing_comments: [], leading_comments: [], end_of_expression: [newlines: 1, line: 1, column: 20], line: 1, column: 1], [{:__aliases__, [trailing_comments: [], leading_comments: [], last: [line: 1, column: 11], line: 1, column: 7], [:App, :PullStats]}]}]}
    (recode 0.7.2) lib/recode/task/alias_order.ex:46: Recode.Task.AliasOrder.do_run/3
    (elixir 1.17.1) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (recode 0.7.2) lib/recode/runner/impl.ex:55: Recode.Runner.Impl.run/3
    (elixir 1.17.1) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.17.1) lib/mix/tasks/format.ex:668: Mix.Tasks.Format.format_file/2
    (elixir 1.17.1) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.17.1) lib/task/supervised.ex:36: Task.Supervised.reply/4
```

**Comment by NickNeck** [comment]
Thanks for reporting. I will have a look. Can you post your `.iex.exs`?

**Comment by ndan** [comment]
`.iex.exs` looks like this:
```elixir
alias App.PullStats
```

I've bypassed this issue by updating the `.formatter.exs`:

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/ed7b2515-5a84-4322-803b-3d66573002d1">

**Comment by NickNeck** [comment]
I have made a new release. This should fix the problem.

**Comment by ndan** [comment]
Wow, that was fast. Thank you so much!
